### ISSUE TITLE
schema version?

### ISSUE THREAD

**Issue by JasonSwindle** [jsonresume/resume-schema#104] opened 2014-07-13 23:34 UTC
Howdy,

We should use [Semantic Versioning](http://semver.org/), and have that defined in the JSON.  That way, when the parser hits that, it knows what fields should be defined.

```json
  "schemaVersion": {
    "semver": "0.0.1" 
  },
```

What do you think?

Thanks,
_Jason Swindle_

**Comment by stp-ip** [comment] 2015-09-10 10:38
This is not yet in the schema. The actual schema is versioned, but the json for each resume does not reflect or store any version. So a field such as the proposed:
  "schemaVersion": {
    "semver": "0.0.1" 
  },
Is still needed

**Comment by olivif** [comment] 2015-12-25 15:23
dupe of #49 ?

**Comment by aloisdg** [comment] 2015-12-25 15:51
Yep. You can close this thread as duplicate.

**Comment by olivif** [comment] 2015-12-25 15:52
:+1:

**Closed by olivif** 2015-12-25 15:52 UTC
