### ISSUE TITLE
Empty end date in work experience causes "Resume json invalid

### ISSUE THREAD

**Issue by argandas** [jsonresume/resume-schema#454] opened 2023-01-14 06:50 UTC

**Comment by ajmarkow** [comment] 2023-02-02 19:21
I noticed this as well. Is there a keyword we can use for currently, or present?

**Comment by ajmarkow** [comment] 2023-02-02 19:24
This is sort of a dupe of #410 I realize

**Comment by thomasdavis** [comment] 2023-05-15 11:41
The other thread covers the reasoning. The invalid JSON error by OP was likely caused by another issue.

**Closed by thomasdavis** 2023-05-15 11:41 UTC
