### ISSUE TITLE
add keywords and summary to core objects

### ISSUE THREAD

**Issue by francescoes** [jsonresume/resume-schema#191] opened 2015-09-06 09:03 UTC
Building a theme I was thinking that It would be great to have fields 'summary' and 'keywords' for (almost) every item. May be some one would like to add keywords to his work experience (like the skills he acquired) or add summary to education (issue #185) or to interests.

Finally I propose to add the field `summary` to:

- interests
- education 

and to add the filed `keywords` to:

- publications
- volunteer
- work

**Comment by stp-ip** [comment] 2015-09-10 12:48
I would say that the easiest part would be to name them labels not keywords and have hidden and public ones. These could be made available to all the different sections and even be used for filtering on the presentation layer. Show only "_professional" sections/items.

**Comment by francescoes** [comment] 2015-09-10 12:55
I didn't get your point.

Keywords should be used for consistency with the other sections, why to create a new name 'label'

What do you mean for hidden and public? 
Everything is optional in the cv.

**Comment by stp-ip** [comment] 2015-09-10 13:10
There were various discussions about the ability for meta data tags. Also there was the suggestion for tagging #170, which in my opinion correlates with your keywords suggestion.
Instead of using the specific keywords or tagging suggestions "label" seemed the less specific naming for all these suggestions.
So instead of keywords, tagging and meta data tags one would just use labels.
Labels can be public "public_label" and a meta data label such as "_hidden_label". Hidden labels could be used for sorting, excluding etc. on the presentation layer. Hope that makes my suggestion clearer.

**Comment by francescoes** [comment] 2015-09-10 14:43
You suggestion is now clear.

I'm proposing elements that should be included in the schema as 'standard' (then the schema allows to add the elements you wish). 

The keywords would be always visible, then the tagging (that it is a great idea) should be always not visible and used in html meta information (as microdata or RDF, etc.).

In conclusion the tagging (or labels) and the keywords are two distinct concept and they should be discussed separately

**Comment by stp-ip** [comment] 2016-02-21 14:38
We have a new issue open for a summary like addition to core objects/sections #223.

And in addition to this we agreed on having keywords. The specifics still need to be finalized, but most of the discussion is located in #203.

Closing for now. If you think the issue is not progressed on in the linked issues, please feel free to reopen or comment in the specific issues.

**Closed by stp-ip** 2016-02-21 14:38 UTC
