### ISSUE TITLE
Extend skills with 2 new properties

### ISSUE THREAD

**Issue by Gordonby** [jsonresume/resume-schema#284] opened 2017-06-17 00:04 UTC
I'd like to see the addition of 2 new properties to skills.
Category, to enable using skills for both high level skills "Application Architecture" and more granular level "c#".  The category would enable the consuming applications to be able to separate these skills for display.  The second would be a score or weight property for the consuming application to be able to order the skill, something that level as a text field isn't quite capable of but could be bent to do.

Current;
    {
      "name": "Application Architecture",
      "level": "Master",
      "keywords": []
    },

Proposed
    {
      "name": "Application Architecture",
      "level": "Master",
      "category": "High level",
      "score" : 50,
      "keywords": []
    },

**Comment by stp-ip** [comment] 2017-08-30 10:51
I disagree on the category addition. Seems too focused on Developers. Any other examples, where that might come in handy? It feels like this could be achieved via keywords and maybe even keyword based sorting/filtering.

I do like the addition of weight to make the ordering explicit.

**Comment by aloisdg** [comment] 2017-09-01 17:04
Weight is a duplicate of level. You can order by level. See #16

**Comment by stp-ip** [comment] 2017-09-01 17:44
Weight is only there fore item ordering so I assume it would not be a duplicate. Only if you always want to order skills by level. You might wanna group them together or something.

**Comment by stp-ip** [comment] 2017-09-01 18:10
Weight is only there fore item ordering so I assume it would not be a duplicate. Only if you always want to order skills by level...

**Comment by aloisdg** [comment] 2017-09-01 19:20
oh right. ok why not. An ordered list would do the job. Oh wait it is json. Well... 😄

**Comment by thomasdavis** [comment] 2020-11-18 14:06
Closing for the above answers to category and score.

**Closed by thomasdavis** 2020-11-18 14:06 UTC
