### ISSUE TITLE
How to create multi-lingual versions of a resume?

### ISSUE THREAD

**Issue by stephen-kruger** [jsonresume/resume-schema#274] opened 2017-01-29 08:49 UTC
It seems the "description" field in the schema does not support any language specifiers.
Would it be possible to include lang/locale information to allow authoring of a multi-lingual resume?

"description" : [
  "en-US" : "my colorful resume",
  "en-UK" : "my colourful resume"
]

**Comment by stp-ip** [comment] 2017-01-29 10:54
There is a proposal to add multilingual features via the meta data section. Basically one provides a base resume and then overwrites various fields with a new language. #35

**Comment by fballiano** [comment] 2019-01-10 09:18
yep, this should be closed as duplicate of #35

**Closed** 2019-01-10 12:58 UTC
